import type { StyleAuthenticitySpec, StyleCategory, StylePresetDefinition, StyleRecipe } from "./style-dna"

const auth = (basis: string[], signatures: string[], mustAvoid: string[], bestFor: string[], a11y: string): StyleAuthenticitySpec =>
  ({ basis, signatures, mustAvoid, bestFor, a11y })
const recipe = (typography: StyleRecipe["typography"], geometry: StyleRecipe["geometry"], surface: StyleRecipe["surface"], density: StyleRecipe["density"], layout: StyleRecipe["layout"], decoration: StyleRecipe["decoration"], contrast: StyleRecipe["contrast"] = "balanced"): StyleRecipe =>
  ({ typography, geometry, surface, density, layout, decoration, contrast })
const preset = (id: string, name: string, category: StyleCategory, description: string, tags: string[], seed: `#${string}`, visualRecipe: StyleRecipe, authenticity: StyleAuthenticitySpec): StylePresetDefinition =>
  ({ id, name, category, description, tags, seed, recipe: visualRecipe, authenticity })

export const STYLE_PRESETS = [
  preset("minimalism", "Minimalism", "product", "Quiet essentials with generous negative space.", ["clean", "quiet", "universal"], "#18181b", recipe("neutral-sans", "subtle", "flat", "comfortable", "document", "none", "soft"), auth(["International modernism", "content-first reduction"], ["few colors", "clear hierarchy", "generous whitespace"], ["empty for its own sake", "low-contrast controls"], ["portfolios", "focused tools", "content products"], "Muted text must remain AA; do not communicate hierarchy with faintness alone.")),
  preset("swiss", "Swiss", "product", "Grid-led typography with objective visual order.", ["grid", "typographic", "modernist"], "#e21d2f", recipe("neutral-sans", "square", "outlined", "default", "grid", "none", "high"), auth(["International Typographic Style", "modular grids"], ["asymmetric grid", "bold sans headings", "red accent"], ["decorative clutter", "soft pill UI"], ["editorial products", "brand systems", "data stories"], "Preserve a logical reading order when the visual grid becomes asymmetric.")),
  preset("editorial", "Editorial", "product", "Publication hierarchy adapted to digital products.", ["serif", "content", "premium"], "#285c4b", recipe("editorial-serif", "subtle", "flat", "comfortable", "document", "none"), auth(["magazine art direction", "newspaper hierarchy"], ["serif display type", "strong scale contrast", "measured columns"], ["generic blog template", "excessive centered copy"], ["publishing", "reports", "storytelling"], "Keep body measure near 45–75 characters and never use display faces for dense UI labels.")),
  preset("functional-minimalism", "Functional Minimalism", "product", "Reduced visuals with dense practical utility.", ["utility", "clean", "efficient"], "#334155", recipe("neutral-sans", "subtle", "outlined", "compact", "dashboard", "none"), auth(["industrial design", "task-first software"], ["visible structure", "restrained accent", "compact controls"], ["hidden affordances", "ornamental whitespace"], ["admin tools", "operations", "productivity"], "All interactive boundaries must remain visible without relying on hover.")),
  preset("saas-modern", "SaaS Modern", "product", "Friendly contemporary software with polished cards.", ["saas", "friendly", "conversion"], "#6366f1", recipe("geometric-sans", "rounded", "raised", "default", "dashboard", "none"), auth(["modern B2B SaaS", "component libraries"], ["soft cards", "bright primary CTA", "clear onboarding hierarchy"], ["purple-gradient sameness", "excessive floating cards"], ["SaaS apps", "onboarding", "billing"], "Keep card boundaries and secondary actions distinguishable in both modes.")),
  preset("linear-inspired", "Linear-inspired", "product", "Fast, dark-capable issue tracking precision.", ["productivity", "keyboard", "dark"], "#5e6ad2", recipe("neutral-sans", "subtle", "layered", "compact", "workspace", "glow"), auth(["Linear product UI", "keyboard-first workflows"], ["compact rows", "subtle violet glow", "command affordances"], ["copying brand assets", "glow on every surface"], ["issue trackers", "developer tools", "team workflows"], "Focus states and selected rows need more than subtle luminance shifts.")),
  preset("vercel-inspired", "Vercel-inspired", "product", "Monochrome developer UI with crisp geometry.", ["developer", "monochrome", "precise"], "#000000", recipe("neutral-sans", "subtle", "outlined", "default", "dashboard", "none", "high"), auth(["Vercel dashboard patterns", "Swiss restraint"], ["black-white palette", "hairline borders", "precise type"], ["brand-logo imitation", "gray-on-gray ambiguity"], ["developer platforms", "deployments", "infrastructure"], "Use shape, label, or icon in addition to color for deployment states.")),
  preset("stripe-inspired", "Stripe-inspired", "product", "Information-rich commerce UI with luminous accents.", ["fintech", "polished", "data"], "#635bff", recipe("humanist-sans", "rounded", "raised", "default", "dashboard", "mesh"), auth(["Stripe product surfaces", "fintech information design"], ["indigo accent", "layered data cards", "precise tables"], ["marketing gradients inside core tasks", "weak numeric alignment"], ["payments", "fintech", "analytics"], "Numbers require tabular alignment and status colors require redundant labels.")),
  preset("notion-inspired", "Notion-inspired", "product", "Document-first workspace with calm neutral controls.", ["documents", "blocks", "calm"], "#37352f", recipe("neutral-sans", "subtle", "flat", "comfortable", "document", "none", "soft"), auth(["Notion workspace patterns", "block editors"], ["document canvas", "muted toolbar", "lightweight blocks"], ["copying proprietary icons", "invisible block actions"], ["knowledge bases", "notes", "wikis"], "Reveal-on-hover controls must also appear on keyboard focus and touch.")),
  preset("enterprise-dense", "Enterprise Dense", "product", "High-throughput interfaces for expert operators.", ["enterprise", "dense", "tables"], "#185fa5", recipe("neutral-sans", "subtle", "outlined", "compact", "workspace", "none"), auth(["enterprise information systems", "expert workflows"], ["dense tables", "persistent navigation", "explicit labels"], ["tiny hit targets", "decorative cards around every group"], ["ERP", "CRM", "operations"], "Maintain 44px touch targets where relevant even when visual rows are compact.")),

  preset("bento-grid", "Bento Grid", "layout", "Modular unequal cards organized into a strong grid.", ["grid", "cards", "modular"], "#2563eb", recipe("geometric-sans", "rounded", "raised", "comfortable", "grid", "none"), auth(["Japanese bento composition", "modular dashboards"], ["varied spans", "strong card hierarchy", "aligned gutters"], ["random card sizes", "every card competing equally"], ["dashboards", "landing pages", "feature overviews"], "Responsive reordering must preserve reading and focus order.")),
  preset("card-first", "Card-first", "layout", "Every major object has a clear contained home.", ["cards", "objects", "scannable"], "#0f766e", recipe("neutral-sans", "rounded", "raised", "default", "dashboard", "none"), auth(["object-oriented UI", "modular component systems"], ["clear card anatomy", "repeatable metadata", "consistent actions"], ["nested card soup", "excessive shadows"], ["marketplaces", "project galleries", "content feeds"], "Card titles, actions, and boundaries must remain perceivable at 200% zoom.")),
  preset("cinematic-mission-control", "Cinematic Mission Control", "layout", "Wide-screen operational overview with dramatic focus.", ["operations", "wide", "cinematic"], "#22d3ee", recipe("geometric-sans", "subtle", "layered", "compact", "dashboard", "glow", "high"), auth(["broadcast control rooms", "situational-awareness displays"], ["panoramic layout", "hero metrics", "dark layered panels"], ["movie-prop illegibility", "constant motion"], ["NOC dashboards", "live events", "monitoring"], "Motion must respect reduced-motion and critical alerts cannot depend on glow.")),
  preset("canvas", "Canvas", "layout", "Open work surface where content becomes spatial objects.", ["canvas", "creative", "freeform"], "#7c3aed", recipe("neutral-sans", "rounded", "canvas", "default", "canvas", "grid"), auth(["whiteboards", "creative canvases"], ["infinite-feeling surface", "floating tools", "object selection"], ["unbounded keyboard traps", "controls without coordinates"], ["whiteboards", "diagramming", "design tools"], "Provide keyboard pan/zoom, visible selection, and an accessible object outline.")),
  preset("node-based", "Node-based", "layout", "Connected blocks for visual systems and flows.", ["nodes", "flows", "technical"], "#8b5cf6", recipe("mono", "subtle", "outlined", "compact", "canvas", "grid"), auth(["visual programming", "graph editors"], ["ports and edges", "typed nodes", "minimap/navigation"], ["crossing-edge chaos", "color-only port types"], ["automation", "data pipelines", "AI workflows"], "Expose graph structure and connections in a navigable nonvisual representation.")),
  preset("split-pane-workspace", "Split-pane Workspace", "layout", "Resizable simultaneous contexts for expert work.", ["workspace", "panes", "productivity"], "#475569", recipe("neutral-sans", "square", "outlined", "compact", "workspace", "none"), auth(["IDEs", "professional desktop software"], ["persistent panes", "draggable dividers", "contextual toolbars"], ["too many default panes", "unlabeled icon rails"], ["editors", "analytics", "support consoles"], "Dividers need keyboard resizing and panes need landmarks and names.")),
  preset("command-centered", "Command-centered", "layout", "Search and commands lead navigation and action.", ["command", "keyboard", "search"], "#4f46e5", recipe("mono", "subtle", "layered", "compact", "workspace", "none"), auth(["command palettes", "keyboard-driven tools"], ["prominent command input", "shortcut hints", "action history"], ["keyboard-only functionality", "opaque command names"], ["developer tools", "power-user apps", "launchers"], "Every command needs a discoverable pointer/touch path and descriptive text.")),
  preset("timeline", "Timeline", "layout", "Chronology is the primary organizing structure.", ["time", "history", "events"], "#db2777", recipe("humanist-sans", "rounded", "flat", "default", "timeline", "none"), auth(["historical timelines", "activity streams"], ["strong time axis", "grouped events", "clear current point"], ["zigzag decoration", "ambiguous sequence"], ["roadmaps", "audit logs", "project history"], "DOM order must match chronology; dates require machine-readable semantics.")),
  preset("spatial-layering", "Spatial Layering", "layout", "Depth and overlap communicate hierarchy and context.", ["depth", "layers", "immersive"], "#0891b2", recipe("geometric-sans", "organic", "layered", "comfortable", "spatial", "mesh"), auth(["spatial interfaces", "depth-based information design"], ["intentional overlap", "depth cues", "foreground tools"], ["occluded content", "depth conveyed only by blur"], ["maps", "media tools", "immersive dashboards"], "All overlapped content needs reachable focus and sufficient contrast against changing layers.")),
  preset("asymmetric-modular", "Asymmetric Modular", "layout", "Controlled imbalance built from a disciplined module system.", ["asymmetric", "editorial", "modules"], "#dc2626", recipe("display", "square", "outlined", "comfortable", "asymmetric", "none", "high"), auth(["constructivist layouts", "editorial grids"], ["offset modules", "strong anchors", "contrasting scale"], ["arbitrary misalignment", "visual order differing from reading order"], ["campaigns", "portfolios", "editorial homepages"], "Use CSS layout to preserve logical source order across breakpoints.")),

  preset("glassmorphism", "Glassmorphism", "effects-dark", "Frosted translucent layers over meaningful depth.", ["glass", "blur", "layered"], "#a78bfa", recipe("geometric-sans", "rounded", "glass", "comfortable", "spatial", "mesh"), auth(["frosted-glass interfaces", "layered translucency"], ["backdrop blur", "light edge", "color behind glass"], ["transparent text fields", "glass on flat backgrounds"], ["media", "premium dashboards", "overlays"], "Provide opaque fallback and verify contrast against every background region.")),
  preset("liquid-glass", "Liquid Glass", "effects-dark", "Glossy refractive surfaces with fluid contours.", ["glass", "fluid", "premium"], "#60a5fa", recipe("geometric-sans", "organic", "glass", "comfortable", "spatial", "chrome"), auth(["optical glass", "liquid refraction"], ["specular highlights", "fluid edges", "layer refraction"], ["blur-only glass", "busy distortion under text"], ["media controls", "premium consumer apps", "hero experiences"], "Disable distortion behind text and provide reduced-transparency treatment.")),
  preset("soft-spatial", "Soft Spatial", "effects-dark", "Calm depth built with diffuse light and generous forms.", ["soft", "depth", "calm"], "#818cf8", recipe("humanist-sans", "organic", "soft", "spacious", "spatial", "mesh", "soft"), auth(["ambient spatial UI", "soft product rendering"], ["diffuse shadows", "large rounded planes", "quiet gradients"], ["neumorphic low contrast", "excessive blur"], ["wellness", "home control", "consumer tools"], "Controls need explicit boundaries despite the soft surface treatment.")),
  preset("aurora-mesh", "Aurora/Mesh", "effects-dark", "Atmospheric color fields behind restrained content.", ["gradient", "ambient", "colorful"], "#8b5cf6", recipe("geometric-sans", "rounded", "glass", "comfortable", "document", "mesh"), auth(["aurora light", "mesh gradients"], ["large blended color fields", "calm foreground", "tonal depth"], ["rainbow on every element", "text directly on unstable color"], ["landing pages", "AI products", "creative tools"], "Place text on stable opaque or translucent surfaces with tested contrast.")),
  preset("glow", "Glow", "effects-dark", "Focused luminosity emphasizes key actions and state.", ["dark", "luminous", "focus"], "#22d3ee", recipe("geometric-sans", "rounded", "layered", "default", "dashboard", "glow", "high"), auth(["emissive displays", "stage lighting"], ["localized bloom", "dark negative space", "bright focal action"], ["glow everywhere", "blurred small text"], ["gaming", "monitoring", "media"], "Glow cannot be the sole focus/state cue; retain sharp boundaries.")),
  preset("gradient-border", "Gradient Border", "effects-dark", "Colorful edge treatment on otherwise disciplined surfaces.", ["gradient", "border", "premium"], "#ec4899", recipe("neutral-sans", "rounded", "outlined", "default", "dashboard", "gradient-border"), auth(["iridescent materials", "edge lighting"], ["selective gradient outlines", "neutral interiors", "subtle color rotation"], ["gradient text overload", "every border highlighted"], ["AI tools", "premium cards", "upgrade surfaces"], "Maintain a solid high-contrast boundary when gradients become faint.")),
  preset("monochrome-dark", "Monochrome Dark", "effects-dark", "Near-black tonal hierarchy with minimal chroma.", ["dark", "monochrome", "focused"], "#a1a1aa", recipe("neutral-sans", "subtle", "outlined", "compact", "workspace", "none", "high"), auth(["darkroom interfaces", "monochrome modernism"], ["tonal layers", "one restrained accent", "crisp type"], ["indistinguishable grays", "pure black large surfaces"], ["developer tools", "media", "focus apps"], "Adjacent surfaces need measurable luminance separation and visible focus rings.")),
  preset("high-contrast-dark", "High-contrast Dark", "effects-dark", "Black-ground UI with forceful legibility and state.", ["dark", "contrast", "accessible"], "#facc15", recipe("neutral-sans", "square", "outlined", "default", "dashboard", "none", "high"), auth(["high-contrast modes", "night operations"], ["near-white type", "sharp borders", "limited vivid states"], ["large pure-white fields", "neon rainbow states"], ["accessibility modes", "operations", "outdoor/night use"], "Avoid halation with off-white text while maintaining enhanced contrast targets.")),

  preset("neo-brutalism", "Neo-brutalism", "expressive-era", "Playful raw geometry, hard shadows, and loud color.", ["bold", "raw", "playful"], "#ff4d00", recipe("display", "square", "outlined", "comfortable", "grid", "none", "high"), auth(["web neo-brutalism", "graphic poster design"], ["thick outlines", "offset shadows", "clashing accent"], ["unusable raw HTML", "random rotation everywhere"], ["creator tools", "youth brands", "campaigns"], "Strong colors still need contrast testing; offset shadows cannot replace focus states.")),
  preset("maximalism", "Maximalism", "expressive-era", "Layered color, scale, and ornament held by hierarchy.", ["bold", "layered", "ornate"], "#d946ef", recipe("display", "mixed", "layered", "comfortable", "asymmetric", "texture", "high"), auth(["maximalist graphic design", "decorative arts"], ["multiple scales", "rich palette", "intentional ornament"], ["everything equally loud", "unstructured color noise"], ["culture", "fashion", "events"], "Provide a calm reading surface and preserve predictable focus order.")),
  preset("tactile-maximalism", "Tactile Maximalism", "expressive-era", "Rich physical textures, depth, and oversized controls.", ["tactile", "texture", "bold"], "#ea580c", recipe("display", "organic", "raised", "comfortable", "asymmetric", "texture"), auth(["physical collage", "material craft"], ["paper/ink texture", "chunky depth", "touchable controls"], ["photoreal texture behind copy", "fake affordances"], ["food", "music", "creative retail"], "Texture intensity must reduce behind text and at high-contrast preference.")),
  preset("collage-scrapbook", "Collage/Scrapbook", "expressive-era", "Cut-paper composition with personal, collected energy.", ["collage", "paper", "personal"], "#db2777", recipe("display", "mixed", "layered", "spacious", "asymmetric", "texture"), auth(["zines", "analog scrapbooks"], ["cutout layers", "tape/label motifs", "mixed image frames"], ["random unreadable rotation", "decorative text as essential content"], ["portfolios", "communities", "campaign stories"], "Keep essential content in semantic text and cap rotation for readability.")),
  preset("hand-drawn", "Hand-drawn", "expressive-era", "Human linework softens a structured interface.", ["sketch", "human", "friendly"], "#2563eb", recipe("humanist-sans", "organic", "outlined", "comfortable", "document", "hand-drawn"), auth(["sketchbooks", "illustrated interfaces"], ["imperfect strokes", "annotation marks", "warm copy"], ["illegible handwritten body type", "wobbly layout alignment"], ["education", "workshops", "family products"], "Use handwriting only for display accents; controls and body copy stay highly legible.")),
  preset("retrofuturism", "Retrofuturism", "expressive-era", "Past visions of technology rendered as modern UI.", ["retro", "future", "chrome"], "#7c3aed", recipe("display", "mixed", "layered", "default", "dashboard", "chrome", "high"), auth(["space-age graphics", "80s/90s computer futures"], ["chrome accents", "star/grid motifs", "optimistic display type"], ["generic synthwave neon", "illegible sci-fi labels"], ["entertainment", "AI concepts", "events"], "Keep novelty type out of dense controls and allow effects to be disabled.")),
  preset("terminal", "Terminal", "expressive-era", "Command-line discipline with phosphor-screen character.", ["mono", "developer", "command"], "#38d878", recipe("mono", "square", "outlined", "compact", "workspace", "none", "high"), auth(["Unix terminals", "phosphor displays"], ["monospace type", "prompt language", "green/amber accent"], ["fake scanlines over text", "all-caps paragraphs"], ["developer tools", "security", "CLI companions"], "Do not reduce font size to mimic terminals; expose commands with descriptive labels.")),
  preset("industrial", "Industrial", "expressive-era", "Utilitarian panels, labels, and engineered rhythm.", ["utility", "rugged", "technical"], "#d26722", recipe("mono", "square", "outlined", "compact", "dashboard", "grid", "high"), auth(["industrial controls", "technical labeling systems"], ["strong dividers", "stencil-like labels", "safety accent"], ["hazard stripes as decoration", "tiny technical text"], ["manufacturing", "logistics", "hardware tools"], "Safety states must follow established semantics and never rely on striping alone.")),

  preset("material-3-inspired", "Material 3-inspired", "system-reference", "Tonal surfaces and adaptive shape inspired by Material 3.", ["system", "tonal", "adaptive"], "#6750a4", recipe("geometric-sans", "rounded", "raised", "comfortable", "dashboard", "none"), auth(["Material Design 3 public principles", "tonal color systems"], ["tonal containers", "prominent shape", "state layers"], ["claiming official compliance", "old heavy Material shadows"], ["Android products", "cross-platform apps", "consumer utilities"], "Follow minimum target sizes and preserve visible state layers for interaction.")),
  preset("fluent-2-inspired", "Fluent 2-inspired", "system-reference", "Layered, productive UI inspired by Fluent 2.", ["system", "enterprise", "layered"], "#0f6cbd", recipe("humanist-sans", "rounded", "raised", "compact", "workspace", "none"), auth(["Fluent 2 public guidance", "Microsoft productivity patterns"], ["subtle depth", "calm blue accent", "dense command surfaces"], ["claiming official compliance", "acrylic on every panel"], ["enterprise apps", "productivity", "collaboration"], "Command bars need accessible names, overflow behavior, and keyboard navigation.")),
  preset("carbon-inspired", "Carbon-inspired", "system-reference", "Structured enterprise UI inspired by Carbon.", ["system", "enterprise", "structured"], "#0f62fe", recipe("neutral-sans", "square", "flat", "compact", "workspace", "none", "high"), auth(["Carbon Design System public guidance", "IBM enterprise design"], ["2x grid rhythm", "square fields", "strong information hierarchy"], ["claiming official compliance", "mixing arbitrary radius"], ["data platforms", "enterprise", "operations"], "Dense components must retain documented target, focus, and label behavior.")),
  preset("primer-inspired", "Primer-inspired", "system-reference", "Developer-focused clarity inspired by Primer.", ["system", "developer", "practical"], "#0969da", recipe("neutral-sans", "subtle", "outlined", "compact", "workspace", "none"), auth(["Primer public design guidance", "GitHub workflow patterns"], ["practical controls", "clear states", "compact data lists"], ["claiming official compliance", "copying proprietary product chrome"], ["developer platforms", "code review", "project management"], "Status colors need icons/text and keyboard interaction must support dense lists.")),
] as const satisfies readonly StylePresetDefinition[]

export type StylePresetId = (typeof STYLE_PRESETS)[number]["id"]
export const STYLE_PRESET_COUNT = STYLE_PRESETS.length
export const STYLE_PRESET_IDS = STYLE_PRESETS.map((item) => item.id) as StylePresetId[]

const byId = new Map<string, StylePresetDefinition>(STYLE_PRESETS.map((item) => [item.id, item]))
const byName = new Map<string, StylePresetDefinition>(STYLE_PRESETS.map((item) => [item.name.toLowerCase(), item]))

/** Maps the former 24-preset names to their closest canonical style. */
export const LEGACY_PRESET_MAP: Readonly<Record<string, StylePresetId>> = {
  Editorial: "editorial", Minimal: "minimalism", Brutalist: "neo-brutalism", "Soft UI": "soft-spatial",
  Glass: "glassmorphism", Bento: "bento-grid", "Neo-grotesk": "swiss", Warm: "tactile-maximalism",
  Midnight: "monochrome-dark", Playful: "maximalism", Swiss: "swiss", Corporate: "enterprise-dense",
  Luxury: "editorial", Cyberpunk: "retrofuturism", Pastel: "soft-spatial", Material: "material-3-inspired",
  Retro: "retrofuturism", Terminal: "terminal", Scandinavian: "minimalism", Bauhaus: "asymmetric-modular",
  Japanese: "editorial", Y2K: "retrofuturism", Industrial: "industrial", Organic: "soft-spatial",
}

export function getStylePreset(idOrName: string): StylePresetDefinition | undefined {
  const direct = byId.get(idOrName) ?? byName.get(idOrName.toLowerCase())
  if (direct) return direct
  const legacyId = LEGACY_PRESET_MAP[idOrName]
  return legacyId ? byId.get(legacyId) : undefined
}

export function resolveStylePresetId(idOrName: string, fallback: StylePresetId = "minimalism"): StylePresetId {
  return (getStylePreset(idOrName)?.id as StylePresetId | undefined) ?? fallback
}

export function getStylePresetsByCategory(category: StyleCategory): StylePresetDefinition[] {
  return STYLE_PRESETS.filter((item) => item.category === category)
}

export function searchStylePresets(query: string, category?: StyleCategory): StylePresetDefinition[] {
  const needle = query.trim().toLowerCase()
  return STYLE_PRESETS.filter((item) => (!category || item.category === category) && (!needle ||
    `${item.name} ${item.description} ${item.tags.join(" ")}`.toLowerCase().includes(needle)))
}

export function isStylePresetId(value: string): value is StylePresetId {
  return byId.has(value)
}
